### ISSUE TITLE
Make UML diagram for database

### ISSUE THREAD

**Issue by hinkleydev** [swe21-inventory-group-e/inventory-app#2]

**Comment by ghost** [comment]
``` mermaid
erDiagram
    Item {
        int product_id
        string name
        string description
        string category
        string image_URL
    }
```

**Comment by ghost** [comment]
@hinkleydev - please provide feedback on the UML diagram?

**Comment by ghost** [comment]
```mermaid
erDiagram
    Item {
        int product_id
        string name
        string description
        int price
        string category
        string image_URL
    }
```

**Comment by ghost** [comment]
@hinkleydev - apologies, added the 'price' field now. Please review and let me know next steps?

**Comment by hinkleydev** [comment]
Looks good. My only criticism is that I personally think price should be a `float`, but there's no point making an entire new diagram for that, I'll update the code!

**Comment by ghost** [comment]
Excellent - thank you, that makes perfect sense.
